### ISSUE TITLE
Add option to skip image build e.g skip-build: true/false

### ISSUE THREAD

**Issue by denismatiu** [humanitec/build-push-to-humanitec#38]
We build the image step earlier and don't want to rebuild the image but only pass its name and tag

**Comment by johanneswuerbach** [comment]
While working on this in https://github.com/humanitec/build-push-to-humanitec/pull/40 we had one question, do you still want your image to be pushed to the registry or would you expect the action to take care of this?

**Comment by denismatiu** [comment]
@johanneswuerbach  No, just passing the name and image tag. Build and pushing the image is done in another step in our case

**Comment by johanneswuerbach** [comment]
You can now provide an existing image using `existing-image`. In case the image is already pushed to the registry, the provided `version` and the `:version` tag must be matching.

E.g.
```yaml
uses: humanitec/build-push-to-humanitec@v1
with:
  existing-image: europe-west3-docker.pkg.dev/gcp-project/repository/repo:5
  external-registry-url: europe-west3-docker.pkg.dev/gcp-project/repository
  version: 5
```
